"""Seed the Agents Marketplace with 4 demo-ready agents (M9.S4 / FR-26).

Run from the backend container:

    docker compose -f backend/docker-compose.yml exec web \
        python -m tools.seeds.marketplace

Idempotent: re-running upserts by `slug` so the catalog stays clean.
Only uses currently-shipped trigger types (manual, record) and action
types (noop, log, crm.*) so every agent runs out-of-the-box after
install.
"""

from __future__ import annotations

import os
import sys
from typing import Any

# Make `apps.*` importable when this script is invoked directly via
# `python -m tools.seeds.marketplace` from the repo root.
_BACKEND = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "backend")
if _BACKEND not in sys.path:
    sys.path.insert(0, _BACKEND)

import django  # noqa: E402

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "offside_crm.settings.dev")
django.setup()

from apps.marketplace.models import MarketplaceAgent, MarketplaceAgentCategory  # noqa: E402


SEED_AGENTS: list[dict[str, Any]] = [
    # 1. Lead qualification — fires on new contact, branches on lifecycle
    # stage, creates a high-priority task.
    {
        "slug": "lead-qualification",
        "name": "Lead qualification",
        "icon_emoji": "🎯",
        "category": MarketplaceAgentCategory.LEAD_MANAGEMENT,
        "description": "Auto-creates a follow-up task whenever a new contact lands in lead stage.",
        "long_description": (
            "Triggered when a contact is created. If the contact's lifecycle "
            "stage is 'lead', creates a high-priority follow-up task for the "
            "contact's owner. Edit the task title + priority to match your "
            "team's playbook."
        ),
        "trigger": {"type": "record", "entity_type": "contact", "event": "created"},
        "graph": {
            "start_node_id": "n1",
            "nodes": {
                "n1": {
                    "type": "action",
                    "label": "Log new contact",
                    "config": {"action": "log", "input": {"message": "new contact arrived"}},
                    "next": "n2",
                    "position": {"x": 80, "y": 80},
                },
                "n2": {
                    "type": "branch",
                    "label": "Is a lead?",
                    "config": {"field": "trigger.event", "op": "eq", "value": "created"},
                    "true_next": "n3",
                    "false_next": "end",
                    "position": {"x": 320, "y": 80},
                },
                "n3": {
                    "type": "action",
                    "label": "Create qualify-this-lead task",
                    "config": {
                        "action": "crm.create_task",
                        "input": {
                            "title": "Qualify this lead",
                            "related_type": "contact",
                            "related_id": "{{ trigger.record_id }}",
                            "priority": "high",
                            "created_by_id": "__INSTALLER__",
                        },
                    },
                    "next": "end",
                    "position": {"x": 600, "y": 30},
                },
                "end": {"type": "end", "position": {"x": 900, "y": 80}},
            },
        },
    },
    # 2. Welcome new contact — fires on new contact, drops a welcome note.
    {
        "slug": "welcome-new-contact",
        "name": "Welcome new contact",
        "icon_emoji": "👋",
        "category": MarketplaceAgentCategory.COMMS,
        "description": "Adds a welcome note to every new contact so the next rep has context.",
        "long_description": (
            "Triggered when a contact is created. Attaches a markdown welcome "
            "note to the contact record. Customize the note body to match your "
            "brand voice."
        ),
        "trigger": {"type": "record", "entity_type": "contact", "event": "created"},
        "graph": {
            "start_node_id": "n1",
            "nodes": {
                "n1": {
                    "type": "action",
                    "label": "Drop welcome note",
                    "config": {
                        "action": "crm.create_note",
                        "input": {
                            "body_md": (
                                "## Welcome\n\n"
                                "_Auto-generated by Welcome agent._\n\n"
                                "- Source: {{ trigger.entity_type }}\n"
                                "- Record id: {{ trigger.record_id }}\n"
                            ),
                            "related_type": "contact",
                            "related_id": "{{ trigger.record_id }}",
                            "author_id": "__INSTALLER__",
                        },
                    },
                    "next": "end",
                    "position": {"x": 120, "y": 80},
                },
                "end": {"type": "end", "position": {"x": 480, "y": 80}},
            },
        },
    },
    # 3. Deal stage tracker — record(deal.stage_changed) → log step. The
    # interesting bit is the run history, not the side effect.
    {
        "slug": "deal-pulse",
        "name": "Deal pulse",
        "icon_emoji": "🔔",
        "category": MarketplaceAgentCategory.DEAL_HYGIENE,
        "description": "Logs every deal stage change so you can see who moved what when.",
        "long_description": (
            "Triggered on any deal stage change. Currently writes a "
            "structured log entry; extend with crm.http.request to forward "
            "to Slack/Looker or with crm.create_task for stage-specific "
            "follow-ups."
        ),
        "trigger": {"type": "record", "entity_type": "deal", "event": "stage_changed"},
        "graph": {
            "start_node_id": "n1",
            "nodes": {
                "n1": {
                    "type": "action",
                    "label": "Log stage change",
                    "config": {
                        "action": "log",
                        "input": {
                            "message": "deal stage changed",
                            "deal_id": "{{ trigger.record_id }}",
                            "stage_id": "{{ trigger.stage_id }}",
                        },
                    },
                    "next": "end",
                    "position": {"x": 120, "y": 80},
                },
                "end": {"type": "end", "position": {"x": 480, "y": 80}},
            },
        },
    },
    # 4. Outbound HTTP ping — manual trigger; great way to demo
    # crm.http.request without setting up a webhook URL ahead of time.
    {
        "slug": "outbound-http-ping",
        "name": "Outbound HTTP ping",
        "icon_emoji": "🔌",
        "category": MarketplaceAgentCategory.INTEGRATIONS,
        "description": "Manual workflow that pings a placeholder HTTP endpoint with a deal payload.",
        "long_description": (
            "Manual trigger. Sends a POST to https://httpbin.org/post with a "
            "small JSON body. Demonstrates the crm.http.request action's auth "
            "presets — swap the URL for your own Slack / Looker / Zapier hook."
        ),
        "trigger": {"type": "manual"},
        "graph": {
            "start_node_id": "n1",
            "nodes": {
                "n1": {
                    "type": "action",
                    "label": "POST to httpbin",
                    "config": {
                        "action": "crm.http.request",
                        "input": {
                            "url": "https://httpbin.org/post",
                            "method": "POST",
                            "body": {
                                "source": "offside-marketplace",
                                "agent": "outbound-http-ping",
                            },
                        },
                    },
                    "next": "n2",
                    "position": {"x": 100, "y": 80},
                },
                "n2": {
                    "type": "action",
                    "label": "Log response",
                    "config": {
                        "action": "log",
                        "input": {"status": "{{ n1.status_code }}"},
                    },
                    "next": "end",
                    "position": {"x": 420, "y": 80},
                },
                "end": {"type": "end", "position": {"x": 720, "y": 80}},
            },
        },
    },
]


def upsert_agents() -> int:
    created = 0
    updated = 0
    for spec in SEED_AGENTS:
        slug = spec["slug"]
        # Don't clobber install_count if the agent already exists.
        existing = MarketplaceAgent.objects.filter(slug=slug).first()
        defaults = {k: v for k, v in spec.items() if k != "slug"}
        defaults.setdefault("is_published", True)
        if existing:
            for field, value in defaults.items():
                setattr(existing, field, value)
            existing.save()
            updated += 1
        else:
            MarketplaceAgent.objects.create(slug=slug, **defaults)
            created += 1
    total = MarketplaceAgent.objects.count()
    print(f"marketplace seed: created={created} updated={updated} total={total}")
    return total


if __name__ == "__main__":
    upsert_agents()
