#!/usr/bin/env node
/**
 * OpenAPI codegen — fetches the Django OpenAPI schema and generates the TS client
 * for `@offside/api-client` plus a Swift client copy for `frontend-ios/Generated/`.
 *
 * Default source: http://localhost:8000/api/schema/ (drf-spectacular).
 * Override with OPENAPI_URL env var.
 *
 * Wired up in M1 once the Django backend serves a real schema.
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "../..");
const tsOut = resolve(repoRoot, "packages/api-client/src/generated/schema.ts");
const swiftOutDir = resolve(repoRoot, "frontend-ios/Generated");

const url = process.env.OPENAPI_URL ?? "http://localhost:8000/api/schema/";

console.log(`[codegen] fetching ${url} …`);

try {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`HTTP ${response.status} ${response.statusText}`);
  }
  // M1 will replace this with a real openapi-typescript invocation.
  const schemaText = await response.text();
  mkdirSync(dirname(tsOut), { recursive: true });
  writeFileSync(
    tsOut,
    `// Generated by tools/openapi/codegen.mjs at ${new Date().toISOString()}\n` +
      `// Source: ${url}\n` +
      `// TODO(M1): replace this stub with an openapi-typescript-generated module.\n` +
      `export const rawSchemaText = ${JSON.stringify(schemaText.slice(0, 80) + "…")};\n`,
  );
  mkdirSync(swiftOutDir, { recursive: true });
  console.log(`[codegen] wrote ${tsOut}`);
  console.log(`[codegen] swift out dir ready: ${swiftOutDir} (Swift codegen wired in M6)`);
} catch (err) {
  console.error(`[codegen] failed: ${err instanceof Error ? err.message : String(err)}`);
  console.error(`[codegen] is the Django dev server running at ${url}? (run "pnpm backend:up")`);
  process.exit(1);
}
